### ISSUE TITLE
Question: Unicode normalization for text

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/text#148]
There are cases where a native normalization implementation without a dependency on `text-icu` would be useful. I am fiddling with a Haskell implementation of normalization. I believe it can perform reasonably well and can utilize stream fusion from text.

To me the `text` package looks like the natural home for this implementation. Some related functionality like `toCaseFold` is already present in text. If that sounds reasonable I will build it upon text instead of a separate package.

**Comment by bos** [comment]
It's quite an undertaking to write and maintain normalization code. I wouldn't be opposed to the idea of taking such code, but what I saw in your https://github.com/harendra-kumar/unicode-transforms repo wasn't of the level of quality or completeness that would be necessary to incorporate here.

**Comment by harendra-kumar** [comment]
That code is not complete and there are multiple implementations included on the head of the branch as of now including C, Haskell using String and Haskell using Stream. I wrote a Haskell implementation of just NFD first to benchmark and improve performance before I implement other forms. 

The NFD stream based implementation is  in https://github.com/harendra-kumar/unicode-transforms/blob/master/Data/Unicode/Internal/NormalizeStream.hs . The code is not released but actually in pretty good shape functionally except some polishing to be done. The data structures and some related code is generated from unicode files, it includes and passes the unicode normalization test suite, there is a benchmark comparing with icu and it performs pretty close to icu even beating it in one benchmark. I plan to add a test suite comparing icu normalized strings with this.

Let me finish it first and then we can discuss about incorporating it in text and review the code from that perspective. In the meantime let me know if there are any specific expectations about the code.

**Comment by bos** [comment]
The code generally looks well-structured. Nice work.

Here are the things I'd look for in a high-quality series of commits:
* `QuickCheck` tests that compare normalization results against some reference (presumably ICU?).
* `criterion` benchmarks that also compare against ICU normalization.
* A script that can update the auto-generated data structures when there's a new Unicode release.

I'm sure you've already got all of these in mind, just being explicit about the bar for this :-)

**Comment by harendra-kumar** [comment]
Thanks for the feedback! The last two are already covered:
* flag `bench-icu` enables icu benchmarks. I kept it under a flag because of the dependency on the icu libraries.
* [UCD2Haskell.hs](https://github.com/harendra-kumar/unicode-transforms/blob/master/unicode-data/UCD2Haskell.hs) generates the data structures from unicode db.

The first one definitely needs to be done as I am sure there may be corner cases which the icu implementation will have covered but may not be fully covered in the unicode test suite. After all standards and implementations usually differ in subtle ways.

I will finish the remaining work in my next stint on this.

**Comment by bos** [comment]
That sounds great. Thanks!

**Comment by harendra-kumar** [comment]
Update: I implemented all forms of normalization, added more tests, added quickcheck against ICU implementation. Test coverage is ~100%. I will now work on making the code better and improve perf. I want to figure out if I can reuse more code across compose and decompose. I have not yet optimized compose though its not bad, will need some time to make it as fast as decompose which is closer to the ICU perf.

In the mean time I wanted to discuss a bit about how to integrate this in `text`. Ideally I would like to have transparent normalization by default rather than explicit calls to normalize. When someone is using `text` s/he should not worry about normalization in general. That will fix normalization problems automatically if you are using text. This will require us to keep the text in a normalized form internally e.g. `NFC`. Let me know your thoughts on that.

**Comment by bos** [comment]
Silent normalization sounds rather sketchy to me, because it would be a big change compared to the do-almost-nothing approach of today, where the only thing we do is clobber invalid code points.

The current implementation lets you layer your own policy on top, rather than forcing one upon you. This obviously has disadvantages, but it's at least simple. And I like simple :-)

So what I'd advise is to submit patches that don't try to change the policy, but instead add normalization support – and then worry about policy stuff at some time later.

**Comment by Lysxia** [comment]
5 years later, [unicode-transforms](https://hackage.haskell.org/package/unicode-transforms) is living healthily on Hackage, so this has been resolved :)

Unicode normalization seems a sufficiently well-defined concern to exist in a separate package. Unless maintaining unicode-transforms would somehow benefit from close coordination with text or GHC, I'm making the call of keeping text more bare bones.
