### ISSUE TITLE
Instances for `Text` missing from haddocks

### ISSUE THREAD

**Issue by Blaisorblade** [haskell/text#159]
Concretely: http://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text.html#t:Text does not mention any interesting instance for `Text`. I spent a while wondering how to get `Monoid Text`, until I found the right sources.

The issue is due to haddock for GHC 7.10, and is explained in https://github.com/haskell/haddock/issues/469. This is a haddock issue affecting other packages. While it _is_ haddock's fault, I understand the issue could be fixed by moving the instances into Data.Text.Internal. Would that be an acceptable workaround?

**Comment by bos** [comment]
You're welcome to take a stab at this, but my experience has been that trying to move instances around can involve messing with a lot of other code that they depend on. If you find yourself able to write a small patch, I'll take it, otherwise let's suffer with the GHC 7.10 bug :-)

**Comment by Blaisorblade** [comment]
At a quick glance I do expect one would need to move a significant part of `Data.Text` into `Internals` and reexport it. I'll see if that can be done without too much pain.

**Comment by ezyang** [comment]
One suggestion might be to just move ALL of it to Internals, so there isn't any picking about chunks that are needed. If we want Internals to have the same exports as before, then another strategy is to make a third, un-exposed module, which contains the entirety of what is today Data.Text and Data.Text.Internals, and then export the needed things from both ends.

**Comment by harpocrates** [comment]
Note that this should be fixed in GHC 8.4.1.

**Comment by hvr** [comment]
@harpocrates note that this may already been addressed, if you look at https://hackage.haskell.org/package/text-1.2.3.0/docs/Data-Text.html and scroll to tbe bottom of the page, they're all there

**Comment by harpocrates** [comment]
@hvr the instances in your link are not listed under the declaration for ‘data Text’. In GHC 8.4.1 they will.

**Comment by Blaisorblade** [comment]
Since IIUC this is being fixed properly in haddock (so I understand @harpocrates comment), and neither I nor apparently anybody else plans to workaround the bug (and I agree it’s probably not worth it), I’ll close the issue.

**Comment by RyanGlScott** [comment]
Here's more proof that's in been [fixed in GHC 8.4.1](https://github.com/haskell/haddock/pull/724), in case you had lingering doubts:

![haddock](https://user-images.githubusercontent.com/2364661/35779955-0035df4a-09a3-11e8-8aa6-df74dec6a04a.png)
