### ISSUE TITLE
Add stateful 'span'?

### ISSUE THREAD

**Issue by neongreen** [haskell/text#178]
O(n) indexing makes some algorithms hard to express. For instance, let's say that I want to break a string into words, but avoid breaking parenthesized groups: `"(a b) c [d e]"` becomes `["(a b)", "c", "[d e]"]`. At the moment, this doesn't seem to be easy to write without incurring a 2× performance penalty (though I might be mistaken). So, I propose adding a function along these lines:

```haskell
-- name subject to bikeshedding
statefulSpan :: (a -> Char -> (a, Bool)) -> a -> Text -> (a, Text, Text)
```

**Comment by Yuras** [comment]
Yes, please. It's easy to implement it in terms of [iter](https://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text-Unsafe.html#v:iter), but it's an unsafe. (I have at least one such implementation in my own code, and I'll be happy to replace it with the `statefulSpan`.) Probably the reverse span (iterating from end to start) will also be useful.
