### ISSUE TITLE
Unsafe use of unsafe foreign calls

### ISSUE THREAD

**Issue by bgamari** [haskell/text#180]
It is unsafe to pass `MutableByteArray#`s to `unsafe` foreign calls as GHC may implement these calls as safe foreign calls, resulting in their relocation. See [GHC #8281](http://ghc.haskell.org/trac/ghc/ticket/8281).

**Comment by bgamari** [comment]
Note that I'm not sure I agree with the limitation described in that bug and there seems to be some pressure to change it, but it seems like either way there will need to be a solution for older compilers.

**Comment by Bodigrim** [comment]
Given that the issue with ghci converting `unsafe` to `safe` has been fixed long ago, in GHC 8.4, I belive this can be closed.
