### ISSUE TITLE
Error recovery in utf8 decoding 

### ISSUE THREAD

**Issue by kuk0** [haskell/text#181]
According to http://unicode.org/faq/utf_bom.html#gen8
if there is a sequence of bytes such as
```
110xxxxx 0xxxxxxx
```
which is illegal (bits `110` represent a 2-byte codepoint, so the second byte needs to begin with `10`)

we should: fail completely, or drop or replace the first byte & continue with the second byte
NOT replace the whole 2-byte sequence (which was the previous behaviour)

**Comment by kuk0** [comment]
https://github.com/kuk0/text/commit/004595bae3e85c9f77eeabbca8e9cef96d3c8a34
is fixing this, TODO: the same for streamDecodeUtf8With

**Comment by kuk0** [comment]
https://github.com/bos/text/pull/182

**Comment by bos** [comment]
Thanks for the fix!
