### ISSUE TITLE
Exposing `hexadecimal` in GHCJS

### ISSUE THREAD

**Issue by pindaroso** [haskell/text#193]
I see that the `hexadecimal` function isn't exported when compiling with GHCJS - is there a workaround or anyone working on a contribution? For reference:

https://hackage.haskell.org/package/text-1.2.2.2/docs/src/Data-Text-Lazy-Builder-Int.html#decimal

**Comment by hvr** [comment]
I suspect that GHCJS is modifying the `text` package in their distribution; I'd suggest asking the ghcjs project about this.

**Comment by Bodigrim** [comment]
Not actionable on our side.
