### ISSUE TITLE
decodeUtf8With: Undefined behaviour using non-BMP error-handler replacements

### ISSUE THREAD

**Issue by hvr** [haskell/text#213]
This issue is intended to track progress on supporting non-BMP replacement characters in the `decodeUtf8With` function.

See also comment at https://github.com/haskell/text/commit/ab90c65cdb7cd5bcbd739843b98bb5da515c8bce#diff-1c42d239accd16adcae29f591c519ac6R172

Short History:

 1. 2189300b09ded9e2637a11edb055da32e11328f7 introduces the first version of `decodeUtf8With` affected by this issue
 2. efa87327e5bdb43d5cdc09b5633f7d17b0b0b5d4 `decodeUtf8With` gets rewritten while retaining this this issue
 3. 1780bd7940fe5beed86c071536ec38317345f314 `decodeUtf8With` gets changed to ensure that surrogate code-points get remapped to `U+FFFD`
 4. ab90c65cdb7cd5bcbd739843b98bb5da515c8bce `decodeUtf8With` gets changed to fail non-silently in case of non-BMP replacement characters

**Comment by Bodigrim** [comment]
This has been fixed in course of UTF-8 migration.
