### ISSUE TITLE
Nonlinear runtime performance in lazy text `drop`

### ISSUE THREAD

**Issue by tdammers** [haskell/text#216]
While investigating [GHC issue 14519](https://ghc.haskell.org/trac/ghc/ticket/14519), I found that one particular rewrite rule in `Data.Text.Lazy` seems to trigger exponential amounts of memory allocations under certain usage patterns. One particularly striking example is how the `regex-tdfa-text` library performs very badly when using lazy `Text` (but not strict `Text`, nor any of the other supported types).

The rule in question is this one:

```
"LAZY TEXT drop -> fused" [~1] forall n t.
    drop n t = unstream (S.drop n (stream t))
```

I don't have clear insights into what exactly happens here, but the hypothesis is that when this rule fires, dropping small bits from the beginning of a string now happens at the stream level instead of the chunk level, and depending on other references to the values involved, this may change sharing behavior for the worse. The rule mentioned above has an inverse companion, but it seems that the way they are ordered causes the `drop -> fused` rule to fire, after which `S.drop` is inlined, and thus the companion rule `drop -> unfused` does not fire even when it should.

**Comment by tdammers** [comment]
Two things worth investigating IMO:

1. Look into the ordering in which the rewrites and inlines fire, and see if that can be fixed such that both rewrites fire (or neither). If the inlining happens before or after both rules, then this should happen.
2. Figure out why `S.drop` behaves badly. This could be intrinsic to the whole streaming setup and thus inevitable, but I can also imagine that there might be inefficiencies there that could be fixed.

**Comment by Bodigrim** [comment]
There is no such rewrite rule any longer.
