### ISSUE TITLE
Error when calling Text.take with a negative 'n' value.

### ISSUE THREAD

**Issue by rdwebster** [haskell/text#227]
For example:

```
main :: IO ()
main = print $ T.length $ T.filter isLetter $ T.take (-3) "Hello! How are you doing today?"
```

throws the following error:

```
Data.Text.Array.new: size overflow
CallStack (from HasCallStack):
  error, called at libraries/text/Data/Text/Array.hs:132:20 in text-1.2.3.0:Data.Text.Array
```

The problem only seems to happen with O1 or higher, so it is likely related to the fusion case.

Also, the problem seems to have be introduced somewhere after text-1.2.2.2.

**Comment by hvr** [comment]
A suspect could be cfb82784fb16e982960619af4187e83b07ac3fb2 (which is also suspected to have introduced the #221 regression)

**Comment by llelf** [comment]
> A suspect could be cfb8278

indeed

```diff
 take n0 (Stream next0 s0 len) =
-     Stream next (n0 :*: s0) (smaller len (fromIntegral (max 0 n0)))
+     Stream next (n0 :*: s0) (smaller len (codePointsSize $ fromIntegral n0))
```
```hs
codePointsSize :: Int -> Size
codePointsSize n = Between n (2*n)
```

**Comment by hvr** [comment]
@bgamari does https://github.com/haskell/text/issues/227#issuecomment-411641006 ring any bells?
