### ISSUE TITLE
Bug related to newline conversion fixed by accident?

### ISSUE THREAD

**Issue by nad** [haskell/text#235]
Consider the following code:
```haskell
import Data.Text (Text)
import qualified Data.Text.IO as T
import System.IO

test :: IO Text
test = do
  writeFile "test" "\r"
  h <- openFile "test" ReadMode
  hSetNewlineMode h universalNewlineMode
  T.hGetContents h
```
When I run this code with text 1.2.3.1 (and GHC 8.6.1, under a Unix-like OS) I get the expected result (`"\r"`), but when I use text 1.2.3.0 I get incorrect output (`""`). The changelog entry for text 1.2.3.1 does not seem to contain an entry for this bug, so I am reporting this in case the bug was fixed by accident.

**Comment by quasicomputational** [comment]
I think this is actually #223, which was a pretty serious bug in its own right.

**Comment by Lysxia** [comment]
That does seem to be #223, which is mentioned in the changelog.
