### ISSUE TITLE
Two incomplete-uni-patterns

### ISSUE THREAD

**Issue by ckoparkar** [haskell/text#245]
There are 2 `incomplete-uni-patterns` in this library. Since this warning will soon be enabled by -Wall, we should either a) use `-Wno-...` , or b) case+error.

The offender:
```
d:ds' = map i2d (if ei > 0 then is' else 0:is')
```

in `Data.Text.Lazy.Builder.RealFloat` : [L92](https://github.com/haskell/text/blob/master/Data/Text/Lazy/Builder/RealFloat.hs#L92) and [L120](https://github.com/haskell/text/blob/master/Data/Text/Lazy/Builder/RealFloat.hs#L120).

**Comment by hvr** [comment]
Patches welcome :-)
