### ISSUE TITLE
Improve Data.Text.Encoding docs

### ISSUE THREAD

**Issue by seagreen** [haskell/text#248]
Total functions should come before their partial variants in the Haddocks, and partial functions should be labeled as such.

(This doesn't matter to experienced Haskellers, but is a stumbling point for beginners, especially since they already have trouble with string handling).

**Comment by seagreen** [comment]
If someone more experienced with this library than me wants to take care of this that would be great, if no one does I'll write up a PR.

**Comment by Bodigrim** [comment]
@seagreen a PR would be most welcome.
