### ISSUE TITLE
Utf8 Text

### ISSUE THREAD

**Issue by googleson78** [haskell/text#251]
I am not sure if this is the right place to ask, so excuse me if I'm wrong but:

Is there any chance of this package going to utf8 instead of utf16?

With backpack it could even be possible to abstract away the encoding. Right now there is a package `text-utf8`, but I feel like this is not very sustainable (maintaining two versions of the package).

I am not aware whether the utf16 encoding is required by the libraries committee (?) or something of that sort.

Thanks in advance!

**Comment by hvr** [comment]
@googleson78 The purpose of the `text-utf8` project (see also https://github.com/text-utf8) is to experiment and prototype whether switching `text` to UTF-8 is possible without incurring inacceptable regressions. A next step to push this forward will be to execute https://github.com/text-utf8/META/issues/4 and turn this into a GSOC, as while we do have a mental roadmap of things to do, we lack the time to execute it... ;-)

**Comment by mlugg** [comment]
2 years later, is there any possibility of this happening? text-utf8 seems to be quite dead by this point - how out-of-sync is it, and how close to being mergeable was it before?

**Comment by jberryman** [comment]
#365
