### ISSUE TITLE
use canonical URLs in discussion of instance Data Text

### ISSUE THREAD

**Issue by jwaldmann** [haskell/text#253]
https://hackage.haskell.org/package/text-1.2.3.1/docs/Data-Text.html#t:Data refers to some "google group"  
that I cannot read without being captcha-d and tracked, while the canonical reference is https://mail.haskell.org/pipermail/haskell-cafe/2010-January/072379.html .
The other URL mentioned there should be https://mail.haskell.org/pipermail/libraries/2012-August/018366.html . 

I can send a PR.

**Comment by hvr** [comment]
Please make a PR

**Comment by hvr** [comment]
Partly addressed by 0ee8d1fc981a72f005761afa7016edaf6527fd3a

**Comment by jwaldmann** [comment]
I will make the PR, I'm just busy today.
