### ISSUE TITLE
Drop overlapping ref names

### ISSUE THREAD

**Issue by bgamari** [haskell/text#255]
`1.2.1.3` is both a tag and a branch, which leads to git blowing up in some cases.

**Comment by hvr** [comment]
My usual convention is use `v1.2.3` for tags, and `1.2.3` for branches; but this repo has established a different convention which I've kept up with. I could rename the branches to something like `1.2.3.x` to reduce the clash; do you have an alternative idea?

**Comment by Lysxia** [comment]
Changed branches to tags.
