### ISSUE TITLE
GHC-8.8 compatible release

### ISSUE THREAD

**Issue by phadej** [haskell/text#259]
Things seem to be fixed in `master`, but there are no release.

cc @bgamari

**Comment by hvr** [comment]
Well, GHC 8.8.1 isn't released either yet... ;-)

**Comment by phadej** [comment]
I made a GHC issue for this: https://gitlab.haskell.org/ghc/ghc/issues/16690

Please coordinate with @bgamari so `transformers` fiasko won't happen.

---

I really try to help by making these issues, so they aren't forgotten. If these are no value, feel free to close.

**Comment by bgamari** [comment]
Thank you for opening this ticket, @phadej!

**Comment by bgamari** [comment]
Ping.

**Comment by hvr** [comment]
Ok, so we mostly need a patchlevel release due to 96149a40698fad2e5b3563b7ea127c2604995c89 for GHC 8.8's sake

@bgamari but what about #241 ?

**Comment by bgamari** [comment]
@hvr, it seems like it would be a good idea to merge #241 if you can.

**Comment by bgamari** [comment]
> Ok, so we mostly need a patchlevel release due to [96149a4](https://github.com/haskell/text/commit/96149a40698fad2e5b3563b7ea127c2604995c89) for GHC 8.8's sake

Correct.

**Comment by bgamari** [comment]
@hvr, what can I do to help here? This is becoming quite urgent.

**Comment by hvr** [comment]
@bgamari ebb98f3929360f3abb681dfca4caa8a190f9c5a8 is basically an RC for text-1.2.4.0 to go along with GHC 8.8.1; do you want me to tag it?

**Comment by bgamari** [comment]
Yes, please do.

**Comment by hvr** [comment]
@bgamari see

- https://github.com/haskell/text/releases/tag/v1.2.4.0-rc
- https://hackage.haskell.org/package/text-1.2.4.0/candidate

**Comment by hvr** [comment]
(https://hackage.haskell.org/package/text-1.2.4.0 was already released on Sat Aug 10 2019)
