### ISSUE TITLE
Bug in `split`

### ISSUE THREAD

**Issue by NorfairKing** [haskell/text#266]
``` haskell
T.split (== '\n') "\55810"
["\65533"]
```

**Comment by NorfairKing** [comment]
It's also in `lines`:

```
> Data.Text.lines "\55810"
["\65533"]
```

**Comment by NorfairKing** [comment]
Looks the problem is not in `split`, nor in `lines`, but in the fact that `fromString` doesn't fail.

**Comment by NorfairKing** [comment]
```
> T.unpack $ T.pack "\55810"
"\65533"
```
Even worse, `T.pack` and `T.unpack` are not inverses.

**Comment by hvr** [comment]
@NorfairKing see also https://hackage.haskell.org/package/text-1.2.4.0/docs/Data-Text.html#g:2

**Comment by NorfairKing** [comment]
@hvr, Jup, thanks for the pointer.

**Comment by NorfairKing** [comment]
Related; https://github.com/bos/aeson/issues/731
