### ISSUE TITLE
Build failure with cabal 1.16 and GHC 7.0

### ISSUE THREAD

**Issue by sjakobi** [haskell/text#282]
`text-1.2.4.0` fails to build with cabal 1.16 and GHC 7.0 with the somewhat mysterious error message

```
target `' is not a module name or a source file
```

I have not been able to reproduce the issue with cabal 3.2.

@vdukhovni [reports](https://github.com/haskell/bytestring/issues/213#issuecomment-624969482) getting the same error with cabal 1.18, 1.24 and 2.4.

Context: https://github.com/haskell/bytestring/issues/213

**Comment by vdukhovni** [comment]
For the record, my test failures were under Travis, with `text` built as part `QuickCheck` when `bytestring` is installing build dependencies.  I rechecked the Travis build history, and it seems I actually tried Cabal 1.16, 1.24 and 2.0.

[Cabal 2.0](https://travis-ci.org/github/haskell/bytestring/builds/683608306)
[Cabal 1.24](https://travis-ci.org/github/haskell/bytestring/builds/683605604)
[Cabal 1.16](https://travis-ci.org/github/haskell/bytestring/builds/683623849)

**Comment by sjakobi** [comment]
Switching to cabal 2.4 fixed the issue in bytestring: https://github.com/haskell/bytestring/issues/217

How about bumping `text`'s `cabal-version` to prevent others from running into the buggy cabal-ghc combination?

**Comment by Bodigrim** [comment]
`cabal-version` has been bumped to 2.2 and GHC 7.0 is no longer supported.
