### ISSUE TITLE
Complexity of compareLength

### ISSUE THREAD

**Issue by sjakobi** [haskell/text#284]
The complexity of `compareLength` is given as O(n) (where `n` presumably means the number of characters(?) in the `Text`).

I would have expected the complexity to be O(min(n,c)) where `c` is the `Int` we're comparing the length against. Is that wrong?

**Comment by Bodigrim** [comment]
Given argument names in function's definition, I think that `n` refers to the length we are comparing against.

```haskell
-- | /O(n)/ Compare the count of characters in a 'Text' to a number.
-- Subject to fusion.
--
-- This function gives the same answer as comparing against the result
-- of 'length', but can short circuit if the count of characters is
-- greater than the number, and hence be more efficient.
compareLength :: Text -> Int -> Ordering
compareLength t n = S.compareLengthI (stream t) n
```

**Comment by sjakobi** [comment]
Hm, that doesn't seem fully implausible, but it would be a bit surprising:

In the [haddocks](http://hackage.haskell.org/package/text-1.2.4.0/docs/Data-Text.html#v:compareLength), you can't see that the `Int` is named `n`.

Moreover, the preceding definition for `length` is also annotated with `O(n)`, but there the only argument that it could refer to is a `Text`.

It would be good to clarify this in any case!

**Comment by Bodigrim** [comment]
Well, whatever of them stands for `n` and for `c`, I agree that it should be `min(n,c)` ;)
