### ISSUE TITLE
Suboptimal generated code with OverloadedStrings

### ISSUE THREAD

**Issue by andrewthad** [haskell/text#287]
Consider this minimal use of `OverloadedStrings`:

```
{-# language OverloadedStrings #-}
{-# OPTIONS_GHC -O2 -Wall -ddump-simpl -ddump-to-file -dsuppress-all -fforce-recomp -ddump-cmm #-}

module Example (example) where

import Data.Text (Text)

example :: Text
example = "Hello World"
```

In GHC core, `example` becomes:

```
-- RHS size: {terms: 1, types: 0, coercions: 0, joins: 0/0}
example2 = "Hello World"#

-- RHS size: {terms: 2, types: 0, coercions: 0, joins: 0/0}
example1 = unpackCString# example2

-- RHS size: {terms: 2, types: 0, coercions: 2, joins: 0/0}
example = ($fIsStringText `cast` <Co:2>) example1
```

And further down the compilation pipeline, in cmm, this becomes:

```
==================== Output Cmm ====================

[example1_entry() //  [R1]
         { info_tbls: [(caVo,
                        label: example1_info
                        rep: HeapRep static { Thunk }
                        srt: Just unpackCString#_closure)]
           stack_info: arg_space: 8 updfr_space: Just 8
         }
     {offset
       caVo:
           if ((Sp + -16) < SpLim) (likely: False) goto caVp; else goto caVq;
       caVp:
           R1 = R1;
           call (stg_gc_enter_1)(R1) args: 8, res: 0, upd: 8;
       caVq:
           (_caVl::I64) = call "ccall" arg hints:  [PtrHint,
                                                    PtrHint]  result hints:  [PtrHint] newCAF(BaseReg, R1);
           if (_caVl::I64 == 0) goto caVn; else goto caVm;
       caVn:
           call (I64[R1])() args: 8, res: 0, upd: 8;
       caVm:
           I64[Sp - 16] = stg_bh_upd_frame_info;
           I64[Sp - 8] = _caVl::I64;
           R2 = example2_bytes;
           R1 = unpackCString#_closure;
           Sp = Sp - 16;
           call stg_ap_n_fast(R2, R1) args: 24, res: 0, upd: 24;
     }
 },
 section ""data" . example1_closure" {
     example1_closure:
         const example1_info;
         const 0;
         const 0;
         const 0;
 }]


==================== Output Cmm ====================

[section ""data" . _uaVF_srt" {
     _uaVF_srt:
         const stg_SRT_2_info;
         const $fIsStringText_closure;
         const example1_closure;
         const 0;
 },
 example_entry() //  [R1]
         { info_tbls: [(caVC,
                        label: example_info
                        rep: HeapRep static { Thunk }
                        srt: Just _uaVF_srt)]
           stack_info: arg_space: 8 updfr_space: Just 8
         }
     {offset
       caVC:
           if ((Sp + -16) < SpLim) (likely: False) goto caVD; else goto caVE;
       caVD:
           R1 = R1;
           call (stg_gc_enter_1)(R1) args: 8, res: 0, upd: 8;
       caVE:
           (_caVz::I64) = call "ccall" arg hints:  [PtrHint,
                                                    PtrHint]  result hints:  [PtrHint] newCAF(BaseReg, R1);
           if (_caVz::I64 == 0) goto caVB; else goto caVA;
       caVB:
           call (I64[R1])() args: 8, res: 0, upd: 8;
       caVA:
           I64[Sp - 16] = stg_bh_upd_frame_info;
           I64[Sp - 8] = _caVz::I64;
           R2 = example1_closure;
           R1 = $fIsStringText_closure;
           Sp = Sp - 16;
           call stg_ap_p_fast(R2, R1) args: 24, res: 0, upd: 24;
     }
 },
 section ""data" . example_closure" {
     example_closure:
         const example_info;
         const 0;
         const 0;
         const 0;
 }]
```

One might argue that this only gets evaluated once and so it doesn't really matter, but the generated code needed to call these functions *does* bloat the resulting binary with something that really doesn't need to be there. There is a [more detailed analyses](https://github.com/haskell/bytestring/pull/191#issuecomment-554060985) of a similar problem the `bytestring` suffers from (one that will be resolved soon!), and I won't attempt to perform the same estimations here. There are some important differences between `text` and `bytestring`. Generally, less constant folding is possible because the elements in UTF-16-backed `Text` are variable width, not fixed width. However, two arguments presented in the `bytestring` issue tracker are certainly applicable here:

* Performing the decoding at runtime bloats the size of executables
* Performing the decoding at runtime prevents GHC from knowing the data constructor at compile time. This prevents some optimizations like worker wrapper.

And there's a third issue a little more relevant here than in `bytestring`: GHC is unable to rewrite pattern matches that scrutinize a known text value (the "case of known data constructor") optimization. For example:

```
example :: Text
example = "Hello World"

foo :: Bool
foo = case example of
  "Hello World" -> True
  _ -> False
```

Clearly, `foo` is `False`, but GHC cannot figure this out at compile time.

All of these issues can be resolved without any breaking changes to the library, but they require two important changes to GHC:

* GHC needs to [support literal `ByteArray#`s](https://github.com/ghc-proposals/ghc-proposals/pull/292).
* Either `OverloadedStrings` must be redone, or GHC must adding a known-key `primitiveStringLiteralToUtf16ByteArray# :: Addr# -> ByteArray#` function that the compiler knows how to constant fold.

**Comment by Bodigrim** [comment]
This has been improved in https://github.com/haskell/text/pull/373 and releases in `text-2.0`.
