### ISSUE TITLE
Language/Sql/Parser.hs:15:1: error:

### ISSUE THREAD

**Issue by Divyashivakumar10** [haskell/text#289]
I am trying to run parser , using haskell but i am getting the following error  , I am new to this so any help is much apreciated  

root@sql-security-vm-3:~/my-project/sql-parser# stack exec ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> :cd src
Prelude> :load Language.Sql
[1 of 5] Compiling Language.Sql.AST ( Language/Sql/AST.hs, interpreted )
[2 of 5] Compiling Language.Sql.Code ( Language/Sql/Code.hs, interpreted )
[3 of 5] Compiling Language.Sql.AST.Tree ( Language/Sql/AST/Tree.hs, interpreted )
[4 of 5] Compiling Language.Sql.Parser ( Language/Sql/Parser.hs, interpreted )

Language/Sql/Parser.hs:15:1: error:
    Failed to load interface for ‘Text.Megaparsec’
    Use -v to see a list of the files searched for.

Language/Sql/Parser.hs:16:1: error:
    Failed to load interface for ‘Text.Megaparsec.String’
    Use -v to see a list of the files searched for.

Language/Sql/Parser.hs:17:1: error:
    Failed to load interface for ‘Text.Megaparsec.Lexer’
    Use -v to see a list of the files searched for.
Failed, modules loaded: Language.Sql.AST, Language.Sql.AST.Tree, Language.Sql.Code.
*Language.Sql.AST.Tree>

**Comment by sjakobi** [comment]
Your issue looks completely unrelated to this project. These are some places that I think are better suited for this:

* https://www.reddit.com/r/haskellquestions/
* The haskell-beginners channel on this Slack: https://fpchat-invite.herokuapp.com/
