### ISSUE TITLE
Please upload 1.2.4.1 to hackage.

### ISSUE THREAD

**Issue by hamishmack** [haskell/text#309]
GHC 8.10.3 has been released and includes text 1.2.4.1, but this version is not on hackage yet.

**Comment by phadej** [comment]
@hvr  The GHC-8.10.3 is released with `v1.2.4.1-rc1` tag.

**Comment by sjakobi** [comment]
Ping @hvr! :)

**Comment by sjakobi** [comment]
http://hackage.haskell.org/package/text-1.2.4.1

Thanks, Herbert! :)
