### ISSUE TITLE
Failing test `toTitle_1stNotLower`

### ISSUE THREAD

**Issue by Lysxia** [haskell/text#332]
I can reproduce it reliably by just raising the number of random test cases:

```
cabal test --test-options="--quickcheck-tests 10000 -p toTitle_1"
```

```
         t_toTitle_1stNotLower: FAIL
            *** Failed! Falsified (after 1299 tests and 7 shrinks):
            "\4317"
```

My current hypothesis is that the generated file `src/Data/Text/Internal/Fusion/CaseMapping.hs` is outdated (Unicode 9) compared to what base uses (Unicode 12). Can't we reuse functionality in base, possibly adding whatever is missing to base?

(This was also mentioned in passing in https://github.com/haskell/text/pull/326#issuecomment-812489090)

**Comment by Bodigrim** [comment]
Regenerating case mapping would be nice, but it does not help in this case. See discussion at https://github.com/haskell/text/pull/302#issuecomment-817350748 One should exclude Georgian Extended chars from this test.
