### ISSUE TITLE
Potential decoding helpers?

### ISSUE THREAD

**Issue by pdedmon** [haskell/text#341]
Would any of the following definitions be worth adding to Data.Text.Encoding?

```
decodeUtf8Either :: ByteString -> Either UnicodeException Text
decodeUtf8Either = decodeUtf8'
```
```
decodeUtf8Maybe :: ByteString -> Maybe Text
decodeUtf8Maybe = either (const Nothing) Just . decodeUtf8'
```

```
decodeUtf8Lenient :: ByteString -> Text
decodeUtf8Lenient = decodeUtf8With lenientDecode
```

These are simple enough to define ad hoc, but I thought I'd ask anyway, to save myself from having to do so :slightly_smiling_face:.

**Comment by phadej** [comment]
Virtually all my project specific preludes introduce `decodeUtf8Lenient`, so :+1: from me.

**Comment by pdedmon** [comment]
Cool, I'll get a pull request together.
