### ISSUE TITLE
Size hints

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#356]
The semantics of size hints for `Stream`s is a bit unclear at the moment. `Date.Text.Internal.Fusion.Types` is very vague:
https://github.com/haskell/text/blob/9c67dad7ce7ebdfddf5f3bfdd915046c33b68e13/src/Data/Text/Internal/Fusion/Types.hs#L71-L81
In fact we do not rely on size hints to detect empty streams:
https://github.com/haskell/text/blob/9c67dad7ce7ebdfddf5f3bfdd915046c33b68e13/src/Data/Text/Internal/Fusion/Common.hs#L293-L299

Further, `Data.Text.Internal.Size` unambiguously claims that size is measured in code units (which is `Word16`) and says that it is not a hint, but rather upper and lower bounds:
https://github.com/haskell/text/blob/9c67dad7ce7ebdfddf5f3bfdd915046c33b68e13/src/Data/Text/Internal/Fusion/Size.hs#L46-L48

When it comes to setting `Size`, indeed there is a mess: some functions assume that sizes are measured in code units as documentation suggests (e. g., `Date.Text.Internal.Fusion.singleton`), but others think that it is code points (aka `Char`): 
https://github.com/haskell/text/blob/9c67dad7ce7ebdfddf5f3bfdd915046c33b68e13/src/Data/Text/Internal/Fusion/Common.hs#L352-L358
You see, mapping preserves number of characters, but their UTF-16 encoding can get twice as long. 

`Size` is used in two ways:
* To allocate a buffer when converting `Stream` to `Text`. In this case the semantics is of a hint only; we reallocate the buffer, if it proved to be not enough:
https://github.com/haskell/text/blob/9c67dad7ce7ebdfddf5f3bfdd915046c33b68e13/src/Data/Text/Internal/Fusion.hs#L107-L114
* To short circuit evaluation in `compareLengthI`:
https://github.com/haskell/text/blob/9c67dad7ce7ebdfddf5f3bfdd915046c33b68e13/src/Data/Text/Internal/Fusion/Common.hs#L318-L324
Now this usage is problematic, because it relies on `Size` being precise and not just a hint. 

I'd like to settle on a single semantics of size hints and follow it everywhere. There are two possibilities:
* `Size` is just a hint and approximates code units. This works nicely with buffer allocation for unstreaming and allows us to simplify `Data.Text.Internal.Size`: basically, we can put `type Size = Int` and be with it. This however means that we would not be able to short circuit in `compareLengthI`, but I guess it's not the end of the world. 
* `Size` contains precise upper and lower bounds and measures code points. This allows to retain short circuting in `compareLengthI`, but makes it less friendly for unstreaming, which is, I believe, much more important use case. Keeping bounds precise means that in many cases we end up with over-conservative estimates, allocating too large buffers. 

We could have ignored this problem with UTF-16, when the majority of code points consist of one code unit only. But with moving to UTF-8 the issue becomes much more pronounced, that's why I'm raising it now.

**Comment by cartazio** [comment]
It sounds like two different types of info that have accidentally punned together to be the same in the current code but aren’t the same.  

If fusion is more important then it should take priority. 
if tracking both accurately is valuable then perhaps having different fields for both is perhaps worth while?

meta aside: how would we write a Const time compare for text in haskell that doesn’t do a variable time based on which parts of of a string prefix compare as equal or not? Ir downs matter  except in security engineering, but what are the options? I suppose in that case the foldl’ on a pair of text values is one approach.

**Comment by gbaz** [comment]
There should still be some short circuiting possible with code unit approximation, no? I.e. if we know the code units, we can nonetheless estimate the code points as bounded below and above by some n*size? (Depending on the trustworthiness of the approximation itself, of course?)

**Comment by myShoggoth** [comment]
In my experience with UTF fun in the past (admittedly, way in the past), those uses were explicitly broken out into separate calls to disambiguate, because depending on your use case you really need different information. Then you can determine what are the appropriate use cases for code outside of the library and expose the functions explicitly.

If the change in behavior is too much, one option is to deprecate the old one with information about when to call each of the new functions.

**Comment by bgamari** [comment]
Indeed size hints have been a source of bugs in the past: e.g. see #229 and #200. In the latter I tried to clean up the ambiguity in the meaning of the size hint, although it doesn't surprise me that there are still issues. 



> 1. `Size` is just a hint and approximates code units. This works nicely with buffer allocation for unstreaming and allows us to simplify `Data.Text.Internal.Size`: basically, we can put `type Size = Int` and be with it. This however means that we would not be able to short circuit in `compareLengthI`, but I guess it's not the end of the world.

This proposal essentially returns us to the status quo prior to https://github.com/haskell/text/commit/f4fc30cea2a41bd26b6c4445843ba1b3f7d0dde8. This seems fine to me although leaves some potential money on the table and may be harder to reason about as it introduces a value judgement in what constitutes a "good" approximation.

> 2. Size contains precise upper and lower bounds and measures code points. This allows to retain short circuting in `compareLengthI`, but makes it less friendly for unstreaming, which is, I believe, much more important use case. Keeping bounds precise means that in many cases we end up with over-conservative estimates, allocating too large buffers.

IMHO this misses a good alternative: keep `Size` as a precise set of bounds but set an upper bound on the allocation size when the upper and lower bounds are sufficiently different. This is IMHO better than (1) since the heuristics are all in the unstream logic rather than scattered about in each of the combinators' size hint logic.

**Comment by Bodigrim** [comment]
> IMHO this misses a good alternative: keep `Size` as a precise set of bounds but set an upper bound on the allocation size when the upper and lower bounds are sufficiently different.

@bgamari I'm sorry, I'm afraid I don't follow. How would `Size` look like and how it would be transformed by `map`, `filter` and `toTitle`?

**Comment by bgamari** [comment]
> > IMHO this misses a good alternative: keep `Size` as a precise set of bounds but set an upper bound on the allocation size when the upper and lower bounds are sufficiently different.
> 
> @bgamari I'm sorry, I'm afraid I don't follow. How would `Size` look like and how it would be transformed by `map`, `filter` and `toTitle`?

`Size` would continue to represent a set of bounds as it does today:
```haskell
data Size = Between { lower, upper :: Int} | Unknown
```

`map`, `toTitle`, etc. would need to update the size as:
```haskell
newSize = case oldSize of
  Unknown -> Unknown
  Between l u -> Between (l `quot` 4) (u * 4)
```

`filter` would update the size as:
```haskell
newSize = case oldSize of
  Unknown -> Unknown
  Between l u -> Between 0 u
```

**Comment by Bodigrim** [comment]
@bgamari AFAIU under your proposal `lower` and `upper` measure bytes (so `map` can transform 4-byte char into 1-byte, giving us ``l `quot` 4``, and 1-byte char into 4-byte, giving `u * 4`). What should `unstream` allocate as an initial buffer? Just `upper` bytes? 

I think that after even a couple of transformations `lower` and `upper` will be far off to be of any use; imagine `map f . map g . map h`.

**Comment by bgamari** [comment]
> @bgamari AFAIU under your proposal `lower` and `upper` measure bytes (so `map` can transform 4-byte char into 1-byte, giving us `` l `quot` 4 ``, and 1-byte char into 4-byte, giving `u * 4`).

Correct.

> What should `unstream` allocate as an initial buffer? Just `upper` bytes?
> 
I have amended my comment describing one possible implementation for `unstream`.

> I think that after even a couple of transformations `lower` and `upper` will be far off to be of any use; imagine `map f . map g . map h`.

A rewrite rule (`map f . map g === map (f . g)`) could mitigate this in many cases (and, unlike implicit fusion, I think this such a rule doesn't compromise the user's ability to reason about their program's asymptotic performance).

Regardless, I don't think that this is a good argument for compromising the semantics of `Size`. Interpreting `Size` as a set of bounds has the clear advantage of being always well-defined; the library implementor (or an auditor) never needs to "guess" what a sensible hint should be. Not only is this easier to reason about but it's also easy to test (e.g. a `Text` should never yield fewer bytes than the its lower size bound nor more bytes than its upper bound).

**Comment by cartazio** [comment]
Part of the challenge comes from the text Api and haskells char type being
centered around code points rather than graphemes right?

**Comment by Bodigrim** [comment]
Graphemes are a higher level of complexity, which `text` does not even aspire to consider. This is just about code units (aka `Word8` or `Word16`) vs code points (aka `Char`).

**Comment by dcoutts** [comment]
If it helps, I'm pretty sure that the original purpose was just the buffer size hint, as a common-case performance optimisation. The `compareLengthI` must have come along later.

**Comment by Bodigrim** [comment]
> Interpreting `Size` as a set of bounds has the clear advantage of being always well-defined; the library implementor (or an auditor) never needs to "guess" what a sensible hint should be. Not only is this easier to reason about but it's also easy to test (e.g. a `Text` should never yield fewer bytes than the its lower size bound nor more bytes than its upper bound).

I'm sympathetic to this line of thought, but I have hard times to convince myself that this additional complexity buys us anything valuable. Instead of an unboxed `Int` for a hint, we carry `Unknown | Between Int Int`, carefully implement arithmetic over intervals, take care about possible integer overflows (a sequence of `map`s can overflow upper bound pretty quickly) - all of this for what? 

Unstreaming is actually likely to regress, because almost any transformation breaks ``(u - l) < u `quot` 10`` condition. If this is to salvage `compareLengthI`, then note that we can easily restore short circuiting capability for `compareLength :: Text -> Int -> Bool` (because materialized `Text` carries its byte length), it's only streams who take a hit.

**Comment by cartazio** [comment]
I’d say Choose what’s humane for future maintainers and ideally doesn’t
create too much of a regrsssion for the worst case examples we know will
happen.

A lot of ecosystem Libs really should embrace the idea that maintainers
will come and go and have that inform some of how we make choices.

**Comment by Bodigrim** [comment]
Given that we are moving away from stream interface, I'm not interested to pursue this issue any longer.
