### ISSUE TITLE
Fusion Public API Discussion

### ISSUE THREAD

**Issue by Boarders** [haskell/text#358]
If we are to make `Data.Text.Fusion` into a public module where the user can decide which pipelines they would like to fuse then it would be useful to add some combinators for working with Streams easily. I am open to ideas on what that should look like. An initial idea is something like the following: 

```haskell
fuse :: (Stream Char -> Stream Char) -> (Text -> Text)
fuse f t = unstream . f . stream $ t

fuse_ :: (Stream Char -> a) -> (Text -> a)
fuse_ f t = f . stream $ t
```

This means we can say that a user can replace something of the form:

```haskell
T.takeWhile p . T.map f . T.filter $ t
```
with something like:
```haskell
fuse (S.takeWhile p . S.map f . S.filter) $ t
```

Are these functions too trivial to exist or is there a better name / general interface for adding working with fusion. Note that if we define such a `fuse` function then it should have a rule like `fuse f . fuse g = fuse (f . g)` though if the definitions get inlined then it should follow from `stream/unstream fusion`.

**Comment by Bodigrim** [comment]
I'm slightly more inclined to say that `fuse` and `fuse_` do not pass Fairbairn threshold; and using `Stream` should be a conscious and explicit choice, not just "I slapped `fuse` everywhere", so it is acceptable to make it a bit less ergonomic. But I don't have any strong opinion here, either way is fine with me.

With regards to names, maybe `withStream`?

**Comment by Boarders** [comment]
It may be the case that it is no big deal to give explicit control over a given pipeline like you say. I do prefer `withStream` to my choice of names.

**Comment by Boarders** [comment]
After giving this some thought, I think we can just improve the documentation with examples to show how to use the stream interface as an iterator over such functions.
