### ISSUE TITLE
text-1.2.5.0 release

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#359]
We need a new release of `text` to accompany an upcoming GHC 9.2. I've prepared a cut to include as many bug fixes as possible, while avoiding breaking changes. Please take a look at https://github.com/haskell/text/tree/release-1.2.5.0 

Unfortunately, @bgamari asks this to be released as soon as possible, so unless there are specific objections, I'll upload it by the end of the week. 

CC @chessai @emilypi @parsonsmatt @Boarders @Lysxia

**Comment by parsonsmatt** [comment]
Do we have a git hash that we can compare against for the most recent release?

There's no tag for `1.2.4.1`. [This link compares the branch you link with the `1.2.4.0` tag](https://github.com/haskell/text/compare/v1.2.4.0...release-1.2.5.0?expand=1).

**Comment by Bodigrim** [comment]
@parsonsmatt Here is a comparison against `text-1.2.4.1`: https://github.com/haskell/text/compare/1.2.4.1...release-1.2.5.0

**Comment by parsonsmatt** [comment]
lmao, that'll teach me to not read down the list all the way :joy: thank you!

**Comment by bgamari** [comment]
Unfortunately this commit isn't quite `-Wall`-clean:
```
libraries/text/src/Data/Text/Lazy/Encoding.hs:62:1: error: [-Wunused-imports, -Werror=unused-imports]
    The qualified import of ‘Data.ByteString.Unsafe’ is redundant
      except perhaps to import instances from ‘Data.ByteString.Unsafe’
    To import instances alone, use: import Data.ByteString.Unsafe()
   |
62 | import qualified Data.ByteString.Unsafe as B
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bgamari** [comment]
I have opened #360 to fix thsi.

**Comment by Bodigrim** [comment]
Released as https://hackage.haskell.org/package/text-1.2.5.0
