### ISSUE TITLE
Unexpected conversion to surrogate pairs

### ISSUE THREAD

**Issue by jgm** [haskell/text#381]
I assume these results are not intended:
```
ghci> Data.Text.length ("\113822\820" :: Data.Text.Text)
3
ghci> Data.Text.pack ['\113822', '\820']
"\55343\56478\820"
```
This is with ghc 9.2.1 (installed on M1 mac via the binary package ghc-9.2.1-aarch64-apple-darwin) and text 1.2.5.0.

Interestingly, with ghc 9.2.1 on an Intel mac (installed via ghcup) I get different results (same version of text):
```
ghci> Data.Text.length ("\113822\820" :: Data.Text.Text)
2
ghci> Data.Text.pack ['\113822', '\820']
"\113822\820"
```
So I assume this is a bug -- though whether in text or ghc itself, I'm not sure.

**Comment by sjakobi** [comment]
This is very likely due to a bug in GHC. See https://discourse.haskell.org/t/psa-9-2-1-aarch64-miscompilation/3638.

**Comment by Bodigrim** [comment]
Yep, similarly to #380, this is a GHC bug. `text-1.2.5.0` has no platform-dependent code paths for `length`.
