### ISSUE TITLE
extra-libraries for c++ are incomplete

### ISSUE THREAD

**Issue by blackgnezdo** [haskell/text#398]
`text.cabal` has this fragment which likely belongs somewhere in cabal:
```
  if os(windows)
    if arch(x86_64)
      extra-libraries: stdc++-6 gcc_s_seh-1
    else
      extra-libraries: stdc++-6 gcc_s_dw2-1
  else
    if os(darwin)
      extra-libraries: c++
    else
      extra-libraries: stdc++
```

As it stands, the fragment is incomplete and some clang-based operating systems need slightly different libraries for this to work. E.g. ghci in HEAD complains about missing libraries [somewhat incomprehensibly](https://gitlab.haskell.org/ghc/ghc/-/issues/20870).

I'll try to cook up a patch which solves the immediate problem, but it's likely not at the right level.

**Comment by Bodigrim** [comment]
Yeah, I see this warning for FreeBSD build, when `cabal` hits Template Haskell (and thus runs `ghci`):
```
<no location info>: warning: [-Wmissed-extra-shared-lib]
    Shared object "libstdc++.so" not found, required by "ghc"
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).
```
https://cirrus-ci.com/task/6590603153637376?logs=main#L194

Indeed, linking to C++ stdlib should better be solved by cabal/ghc, not on library level. Choice between `c++` and `stdc++` should be guided by availability of gcc / clang, not by OS. 

I assume extending `os(darwin)` with `os(darwin) || os(freebsd) || os(openbsd)` should help, a PR would be most welcome.

Alternatively, one can disable `simdutf` flag (in which case it is recommended to force `bytestring >= 0.11.2.0`).
