### ISSUE TITLE
undefined reference to `__get_cpuid_count'

### ISSUE THREAD

**Issue by sjakobi** [haskell/text#408]
Full error:

```
Linking /__w/cborg/cborg/dist-newstyle/build/x86_64-linux/ghc-8.0.2/cbor-tool-0.2.2.0/x/cbor-tool/build/cbor-tool/cbor-tool ...
/github/home/.cabal/store/ghc-8.0.2/text-2.0-c46353126c38c0002af2c33e37c7db2e3337f6f1aea8545686900c7ce3780a4e/lib/libHStext-2.0-c46353126c38c0002af2c33e37c7db2e3337f6f1aea8545686900c7ce3780a4e.a(measure_off.o): In function `has_avx512_vl_bw':
measure_off.c:(.text+0x2df): undefined reference to `__get_cpuid_count'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```

This happened while building `cbor-tool` in [a GHA action build](https://github.com/well-typed/cborg/runs/4882566178?check_suite_focus=true) using

```
    container:
      image: buildpack-deps:xenial
```

I suspect that this build used an old GCC version which doesn't provide the `__get_cpuid_count` function.

**Comment by sjakobi** [comment]
While searching for the error message, I found https://github.com/vusec/ridl/issues/11. In this case they used assembly to workaround the missing function.

**Comment by Bodigrim** [comment]
@sjakobi does #401 fixes the issue?

**Comment by sjakobi** [comment]
> @sjakobi does #401 fixes the issue?

Yes it does. :) I've tested this in https://github.com/sjakobi/cborg/pull/1.
