### ISSUE TITLE
Switch simdutf flag to off by default

### ISSUE THREAD

**Issue by gbaz** [haskell/text#412]
Given the difficulties consistently linking with c++ under the current capabilities of ghc, it seems it would be better for text to _not_ use the simdutf flag by default, allowing users who Know What They Are Doing to enable it for extra juice when they so desired.

(cf https://gitlab.haskell.org/ghc/ghc/-/issues/20010)

cc @bgamari

**Comment by Bodigrim** [comment]
Our CI does not witness difficulties with C++ linking: Cabal is able to build it absolutely fine. If GHC bindist struggles with it, it can disable the flag on its own.

**Comment by gbaz** [comment]
As per the discussion in https://github.com/haskell/cabal/issues/8007 it appears that the current solution is extremely fragile and things only get worse the more different systems and versions need to be supported. The fact that you have stabilized the CI _for now_ does not mean that this is a long-term tenable approach.

**Comment by Bodigrim** [comment]
Current solution works across all CI jobs, and there are plenty of them, covering a wide range of systems. Users of exotic systems can contribute a CI job to ensure proper future support. 

It seems unreasonable to penalise the majority of users because of this.

**Comment by chessai** [comment]
Perhaps we could compromise and have it enabled by default on common systems where it works with no problems?

**Comment by Bodigrim** [comment]
Well, I'm yet to hear on which systems `simdutf` does not work. We can either submit a fix or disable `simdutf` flag on them indeed.
