### ISSUE TITLE
text-test-data repo

### ISSUE THREAD

**Issue by askeblad** [haskell/text#419]
@Bodigrim

could a write-up be made of how to use `haskell/text-test-data`

or, in lieu of that, an Organization member assessment be made to deprecate that repo

**Comment by Bodigrim** [comment]
@askeblad it's already in README:
https://github.com/haskell/text/blob/eeddd25fd3a80228a4a65a6961261d52297cd00c/README.markdown?plain=1#L16-L21

**Comment by askeblad** [comment]
other repos' README due for update

text-test-data/README.markdown

```markdown
For instructions, read
[`tests/README.markdown`](https://bitbucket.org/bos/text/src/tip/tests/README.markdown)
in the [`text`](https://bitbucket.org/bos/text) repository.
```

**Comment by Bodigrim** [comment]
Feel free to update `text-test-data/README.markdown` in course of https://github.com/haskell/text-test-data/pull/2

**Comment by askeblad** [comment]
> update `text-test-data/README.markdown`

@Bodigrim can a decision be made on https://github.com/haskell/text/pull/420 prior to an additional commit on https://github.com/haskell/text-test-data/pull/2

FWIW, the `text-test-data` PR (thus far) results in this.

![text-test-data](https://user-images.githubusercontent.com/74082607/162582495-bc46efc4-9ede-4270-a742-85f3a64119d8.png)

Which of course isn't accurate in terms of number of flat file lines in the repo.

```
$ wc -m text-test-data/Makefile
325 text-test-data/Makefile
$ wc -m text-test-data/tiny.txt
5 text-test-data/tiny.txt
$ 
```

Solely removing `text-test-data/.hgignore` results in Linguist listing the repo contents as Makefile 100%.

**Comment by askeblad** [comment]
@Bodigrim 

https://github.com/haskell/text/pull/421

if you have write authority over `haskell/text-test-data` the open PR there is ready to merge
