### ISSUE TITLE
Is there a release that includes commit "Fix missing stdatomic.h"

### ISSUE THREAD

**Issue by AndreasPK** [haskell/text#427]
In ghc-9.4 we would like to include this fixed in the shipped text version. But I'm not sure if there is a release with this fix already.

If there isn't could one be made?

**Comment by Bodigrim** [comment]
Please use HEAD instead, I'll make a release closer to GHC 9.4 RC1. There are two outstanding issues, which must be resolved before release:

* Submit 5a43fec, feel free to raise a PR.
* Support `wasm32-wasi` arch (#205), which is currently blocked on Cabal side.

**Comment by mpickering** [comment]
Why do we need to support wasm32-wasi arch for 9.4? Wasm/JS support in ghc is targetted for 9.6.

**Comment by Bodigrim** [comment]
@mpickering nevermind, `wasm32-wasi` obstacle has been resolved.

**Comment by Bodigrim** [comment]
Released as `text-2.0.1`.
