### ISSUE TITLE
text-1.2.5 is not buildable with GHC 9.4.1

### ISSUE THREAD

**Issue by wz1000** [haskell/text#449]
The bounds for `ghc-prim` and `template-haskell` need to be bumped to allow versions `0.9` and `2.19.0.0` respectively.

It builds after bumping the bounds.

**Comment by Bodigrim** [comment]
@wz1000 GHC 9.4 is supposed to use `text-2.0`. Why do you need to build `text-1.2.5.0` with it?

**Comment by wz1000** [comment]
Many programs may have constraints or other restrictions which require older versions of `text`.

In my case, see https://gitlab.haskell.org/ghc/ghc/-/issues/21787

**Comment by jberryman** [comment]
We'd also appreciate this.

**Comment by Bodigrim** [comment]
Closing, since the static build issue has been resolved in #453. Feel free to reopen if there are other reasons justifiying revisions for `text-1.2.5.0`.

**Comment by mpickering** [comment]
@Bodigrim Please can you just update the bounds on hackage to allow these newer versions? There doesn't need to be a new release. Should we ask a hackage trustee to do it for us?

**Comment by Bodigrim** [comment]
I'm reluctant to prolong lifespan of `time-1.2` series without a good reason. @wz1000 what kind of migration are we talking about?
