### ISSUE TITLE
Linking against `gcc_s` is problematic on windows

### ISSUE THREAD

**Issue by wz1000** [haskell/text#456]
When the path doesn't include `gcc_s.dll` then binaries linked against text will silently fail.

`text-2.0` links against `gcc_s.dll` when `simdutf` is unset:

https://github.com/haskell/text/blob/971051b597aa8ca240ad64b06baa896134d5177a/text.cabal#L196-L198

Related GHC ticket: https://gitlab.haskell.org/ghc/ghc/-/issues/21196

CI job that demonstrates the failure: https://github.com/haskell/text/runs/7337239414

**Comment by bgamari** [comment]
As noted in the comment, this `extra-libraries` entry was introduced as a mitigation for [GHC #19900](https://gitlab.haskell.org/ghc/ghc/-/issues/19900), which is fundamentally a GHC runtime linker bug. However, as we see here, the medicine is worse than the disease as now all binaries link against `libgcc_s.dll`. This is problematic as `libgcc_s` is a component of msys2, which in general GHC does not depend upon (beyond the msys2 toolchain which is included in the GHC binary distribution for Windows) and won't be in the Windows library/executable search path (`PATH`) (this is the same issue seen in https://github.com/haskell/bytestring/issues/497).

Consequently, I think we should remove the `extra-libraries` entry. This will regress #19900 but we can mitigate it in the short term by ensuring that we do not depend upon operations supplied by `libgcc`, as is done in #453. Once the linking bug is resolving we can reintroduce use of the builtin.

**Comment by Bodigrim** [comment]
Fixed in #453.
