### ISSUE TITLE
Speedups with SIMD

### ISSUE THREAD

**Issue by alt-romes** [haskell/text#469]
I recently came across https://github.com/simdutf/simdutf and was wondering if any of its ideas could be of interest to text and perhaps reused by text

Just throwing it out there for a short discussion.

We can close this issue if it's infeasible or unnecessary/not worth it

**Comment by phadej** [comment]
Simdutf is used in text: it's right there https://github.com/haskell/text/tree/master/simdutf

**Comment by alt-romes** [comment]
Ah! How cool! :-) Thanks

**Comment by Bodigrim** [comment]
@alt-romes we are likely to be one of the first production users of `simdutf`, https://github.com/simdutf/simdutf#usage ;)
