### ISSUE TITLE
Eta expand case conversions

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#500]
According to investigation in https://gitlab.haskell.org/ghc/ghc/-/issues/22886#note_479157, we should apply the following patch for the optimal performance in GHC 9.6:
```diff
-toLower = caseConvert (\w -> if w - 65 <= 25 then w + 32 else w) lowerMapping
+toLower = \xs -> caseConvert (\w -> if w - 65 <= 25 then w + 32 else w) lowerMapping xs
```

**Comment by Boarders** [comment]
I'll give this a look and see if there are any other places where inlining makes sense to convince GHC to inline.
