### ISSUE TITLE
Release for GHC 9.6.1?

### ISSUE THREAD

**Issue by bgamari** [haskell/text#505]
It would be great to get a release in the next couple of weeks for GHC 9.6.1. We are currently using 197bbcb18977593a06b048ad58abe71c6119799e but would be happy to upgrade. If a release isn't feasible in this timeframe then we can instead revert to a revision of 2.0.1 with the bounds bump in 197bbcb18977593a06b048ad58abe71c6119799e.

**Comment by Bodigrim** [comment]
I think `master` branch is good to go. @Lysxia what’s your opinion? Would you like to take management of this release?

**Comment by Lysxia** [comment]
That looks good to me too. If you could handle it this time too that would be great. I may be more free next time.

**Comment by bgamari** [comment]
Thank you both! Let me know when there is a commit and I'll go ahead and bump GHC's submodule.

**Comment by Bodigrim** [comment]
I realised that this TODO needs to be fixed before release:

https://github.com/haskell/text/blob/9c29cf3512605773e4ef1097473b881e005517d1/src/Data/Text/Internal.hs#L257-L261

Not only forcing `xs` in full beforehand does no good, but also shrinking does not really do anything useful, see https://gitlab.haskell.org/ghc/ghc/-/issues/22994.

**Comment by Bodigrim** [comment]
[`text-2.0.2`](https://hackage.haskell.org/package/text-2.0.2) is out, I've raised https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10014.
