### ISSUE TITLE
Add unsafe decoding functions

### ISSUE THREAD

**Issue by oberblastmeister** [haskell/text#515]
```haskell
unsafeDecodeUtf8 :: ByteString -> Text
unsafeDecodeUtf8ByteArray :: ByteArray -> Int -> Int -> Text
```
These functions do not check if the input is valid utf8. `unsafeDecodeUtf8ByteArray` does not check the bounds either.

**Comment by Bodigrim** [comment]
There is a maintenance price to expand API with all helpers possible, I'm reluctant to go this route.

**Comment by Lysxia** [comment]
At least now you can write it as `toText . unsafeFromByteString :: ByteString -> Text` where those are two internal functions from `Data.Text.Internal.StrictBuilder`.

I think it's reasonable that the external API of text shouldn't expose primitives that break internal invariants (if there are any existing examples, I would consider them a historical mistake). They can still be packaged up as a separate library by whoever is willing to take on the extra work. Feel free to reach out to me if you need help with such a package.
