### ISSUE TITLE
Add `encodeUtf8ByteArray`

### ISSUE THREAD

**Issue by oberblastmeister** [haskell/text#516]
```haskell
encodeUtf8ByteArray :: Text -> (ByteArray, Int, Int)
```
This will be faster than doing `encodeUtf8` because we avoid a copy.

**Comment by Bodigrim** [comment]
Just pattern match on `Text` constructor?

**Comment by oberblastmeister** [comment]
We already have `encodeUtf8`, I don't see why we can't have one for `ByteArray`. Touching the unsafe internals just to perform a simple and safe conversion seems overkill.

**Comment by phadej** [comment]
They are internals, but they are not unsafe.

**Comment by oberblastmeister** [comment]
They are unsafe, because if you have the text constructor you can create text that is invalid utf8.

**Comment by Lysxia** [comment]
I wouldn't consider `encodeUtf8ByteArray` to be safe, because it lets you distinguish different representations of the same value. For example, let `x = "a"` and `y = drop 1 "aa"`. We would have `x == y` but `encodeUtf8ByteArray x /= encodeUtf8ByteArray y`.
