### ISSUE TITLE
The new `lift` implementation in text-2.0.1 breaks with `RebindableSyntax`

### ISSUE THREAD

**Issue by lierdakil** [haskell/text#533]
Since text-2.0.1, `lift` implementation for `Text` has changed to, essentially

```haskell
unpackCStringLen# $(bytes) $(lenInt)
```

https://github.com/haskell/text/blob/bc6f4031d6da74bcf97635ac01ac1540e5285672/src/Data/Text.hs#L419-L422

where `lenInt` is an `Int`. The problem here is that `Int` gets lifted into a numeric literal, which gets desugared as `fromInteger <lenInt>`. When using `RebindableSyntax` and there's a non-standard `fromInteger` in scope, this breaks `Text`'s `lift`.

Here's a small repro: https://github.com/lierdakil/text-2.0.1-lift-repro

The only way I could figure a workaround is using an unlifted `Int#` and the primitive constructor. Not too bad, but depends on `GHC.Exts` or somesuch.

Under this suggestion, the relevant code would look something like this (from the top of my head):

```haskell
    let !lenInt@(I# lenIntPrim) = P.fromIntegral len
    TH.appE (TH.appE (TH.varE 'unpackCStringLen#) (TH.litE . TH.bytesPrimL $ TH.mkBytes ptr 0 (P.fromIntegral lenInt))) (conE 'I# `appE` TH.lift lenIntPrim)
```

**Comment by lierdakil** [comment]
Hmm. There is an argument that `Lift Int` should actually insert an `Int` and not an integral literal. But in that case, that's not the only integral type that would need to be changed, pretty much all of them would, and this change is potentially breaking.

**Comment by RyanGlScott** [comment]
Sigh. I really wish that GHC gave us finer-grained control over what language extensions take effect at Template Haskell splices. I struggle to imagine how we'd avoid issues like this one without it (unless we want to avoid ever using `IntegerL`, which seems counter-productive).

**Comment by phadej** [comment]
My 5cents. `Lift Int` could generate `5 :: Int` i.e. explicit type annotation. Alternatively it could generate `I# 5#`.

In meanwhile `text` could do either.
---

The untypedness of `Lift` is known issue. And there aren't cheap way to fix it, as far as I know.

For example, `lift []` will produce `[]`. And that is polymorphic. There isn't `I# 5#` like fix. The only fix is to generate `[] @TheElementType` like code, and that means lifting types - a mechanism which is not cheap to add.

**Comment by lierdakil** [comment]
>  generate `5 :: Int`

Unfortunately, that won't work as GHC will desugar the literal via `fromInteger` regardless of the type signature, so you'll get the equivalent of `fromInteger 5 :: Int`, which doesn't help any.
