### ISSUE TITLE
decodeUtf8 invalid memory read

### ISSUE THREAD

**Issue by luc-tielen** [haskell/text#544]
Hi,

Today I stumbled upon a bug in the `decodeUtf8` function of this package.
I ran the test suite for [eclair-haskell](https://github.com/luc-tielen/eclair-haskell) under valgrind since I was searching for a memory corruption bug, and found this:

![image](https://github.com/haskell/text/assets/3411018/9a3bc2e8-6eea-499a-ab70-33929b43e19a)

The bug ended up being fixed by the following diff, which uses `fromPtr` from `Data.Text.Foreign`: https://github.com/luc-tielen/eclair-haskell/commit/7a2a03909da360ea440a921e1a61097ba2431ca0

The bug can be re-produced by cloning the repo, checking out the previous commit, building the code, and running the tests using valgrind (`valgrind /path/to/test-executable`).

**Comment by Bodigrim** [comment]
@luc-tielen "address ... is 1 bytes before" sounds as https://github.com/haskell/bytestring/issues/620#issuecomment-1775299683. Could you please try `bytestring` HEAD? Does it fix the issue?

**Comment by luc-tielen** [comment]
@Bodigrim Quick reply, nice! Looking at the C code that explains why I was seeing the rror. I was trying it on a string that was only 2 bytes long.

Just checked it after reverting my fix and bumping bytestring.. that seems to fix it!

Guess the real issue was me being behind on updating dependencies :sweat_smile:.

Closing the issue.

**Comment by Bodigrim** [comment]
@luc-tielen `bytestring-0.11.5.3` has not been released yet, so unfortunately users are to be affected for quite some time, sorry for this.

**Comment by luc-tielen** [comment]
@Bodigrim no worries, I have another fix that I posted before. Thanks for helping.
