### ISSUE TITLE
`fromString` from `Data.Text.Lazy.Builder` generates massive amount of code

### ISSUE THREAD

**Issue by TheKK** [haskell/text#549]
The code sample looks like

```haskell
{-# LANGUAGE OverloadedStrings #-}

f :: B.Builder
f = "a cat" <> "a dog" <> "a fish"
```

By using Builder from `bytestring`, the above code generates about 30 lines of core ([compiler explorer](https://godbolt.org/z/8KnY1bMs8)), but we got 2200 lines when switching to `text` ([compiler explorer](https://godbolt.org/z/o515q4zv8))

This becomes a problem since I use [katip](https://github.com/Soostone/katip) for logging and it uses Builder from `text` internally. It's very common to use string literal  to construct Builder while logging.

### `fromString` has INLINE

This is the most obvious reason why it produce so many code. They are inlined three times and it seems that there's nothing (eg. RULE) to make them shorter.

But it's hard for me to tell if removing `INLINE` would make performance worse or not. (And I see no benchmark involve `fromString`)

## Related issue

#19 (it's issue of pre 2.0 `text` which still use RULE to fuse though)

**Comment by Bodigrim** [comment]
Yeah, I suspect that `{-# INLINE fromString #-}` is a bad idea: it should be `{-# INLINABLE fromString #-}` at most. PR is welcome.

**Comment by Bodigrim** [comment]
Checking that the change actually improve Core code bloat would be great.
