### ISSUE TITLE
Add initsNE, tailsNE :: Text -> NonEmpty Text

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#557]
Let's follow the suite of `bytestring`, which provides [`initsNE :: ByteString -> NonEmpty ByteString`](https://hackage.haskell.org/package/bytestring-0.12.0.2/docs/Data-ByteString.html#v:initsNE) and [`tailsNE :: ByteString -> NonEmpty ByteString`](https://hackage.haskell.org/package/bytestring-0.12.0.2/docs/Data-ByteString.html#v:tailsNE). 

This would improve consistency between `bytestring` and `text` and dovetail nicely in the efforts to eliminate `Prelude.head` / `Prelude.tail`, allowing to use `Data.List.NonEmpty.head` in more situations.

For the reference, here is a relevant PR for `bytestring`: https://github.com/haskell/bytestring/pull/557

CC @kindaro.

**Comment by kindaro** [comment]
On it!
