### ISSUE TITLE
Can simdutf be updated please?

### ISSUE THREAD

**Issue by sthen** [haskell/text#563]
The version of simdutf in haskell/text doesn't correctly check if the OS works with AVX512 (resulting in SIGILL on AVX512 machines where there's no OS support). Would it be possible to update to a version after https://github.com/simdutf/simdutf/commit/55b107f609f5f63880db650a92861ae84cb10abe which fixes this please?

**Comment by Bodigrim** [comment]
@sthen PRs welcome.
