### ISSUE TITLE
Lazy splitAt is too lazy?

### ISSUE THREAD

**Issue by Lysxia** [haskell/text#573]
There's a missing bang pattern which makes `Text.Lazy.splitAt` on the empty text lazy in the `Int64` argument. In Core that causes a duplicate worker-wrapper for the first iteration which must be lazy, and the remaining ones which are strict.

Is that accidental? "laziness zeal"? Is that going to be a breaking change?

`splitAtWord` also has this problem but it's internal AFAICT.

[`splitAt`](https://github.com/haskell/text/blob/66fa38f14a5831b659298d69668f2fc86eab797a/src/Data/Text/Lazy.hs#L1238-L1242):

```
splitAt :: Int64 -> Text -> (Text, Text)
splitAt = loop
  where
    loop :: Int64 -> Text -> (Text, Text)
    loop _ Empty      = (empty, empty)
    loop n t | n <= 0 = 
```

**Comment by Bodigrim** [comment]
[`Data.List.splitAt`](https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-List.html#v:splitAt) has notes about laziness, it is not lazy in `n`. I think we should follow the suit.
