### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/text#582]
OpenBSD 7.4 x86_64
cabal 3.10.2.1
ghc 9.2.7
text commit 19725eb45d74e93a1687bd3eb47546755ab1e5ff
[text-2.1.1-tests.log](https://github.com/haskell/text/files/14971827/text-2.1.1-tests.log)

**Comment by Bodigrim** [comment]
Which installation method was used for GHC? From a system package or from ghcup?

**Comment by Bodigrim** [comment]
CI job for OpenBSD (https://cirrus-ci.com/task/6421452751110144) seems fine, so I'm wondering what's the difference in configuration.

**Comment by Lysxia** [comment]
It looks like your tests are being run without optimizations, so it's expected for the inspection tests to fail. Maybe there's a cabal config file somewhere on your system that's disabling `-O` ([default is `-O1`](https://cabal.readthedocs.io/en/3.4/cabal-project.html#cfg-field-optimization))?

**Comment by BebeSparkelSparkel** [comment]
@Lysxia Thanks!
