### ISSUE TITLE
Guidance to conform with "Share empty Text values" change

### ISSUE THREAD

**Issue by phadej** [haskell/text#583]
I noticed this change in `text` and I wonder whether I need to do anything to conform.

In e.g. `aeson` we do create `Text` values manually (using `Data.Text.Internal`, especially when decoding JSON escaping) and I wonder whether I should do anything with empty values. 

There is [`text`](https://hackage.haskell.org/package/text-2.1.1/docs/Data-Text-Internal.html#v:text). Should I always use it? Will something break if I don't?

EDIT: Now as I think of it, the empty `Text` values are not created from JSON escaping as that codepath is not taken for empty string literals. Yet, I'm still curious how much attention we (users of `text` internals) should pay to share empty text values?

**Comment by Bodigrim** [comment]
This is an opportunistic optimisation, but there is no expectation for users to do anything to uphold it. In fact, there is no such expectation even for `text` contributors.

**Comment by phadej** [comment]
Good to know, thanks.
