### ISSUE TITLE
hPutStr NoBuffer uses base hPutChar for Every Character

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/text#584]
I was looking at creating a PR for #446 and noticed that for [strict text hPutStr](https://github.com/haskell/text/blob/3f2a71bb1dad5fd8a64f3743b58d765d985723e2/src/Data/Text/IO.hs#L197) the base function [GHC.IO.Handle.Text.hPutChar](https://hackage.haskell.org/package/base-4.19.1.0/docs/src/GHC.IO.Handle.Text.html#hPutChar) which has a lot of overhead and repeats much work for every character that Data.Text.IO.hPutStr has already done. Is this something that could be improved upon?

This also seems to be the case with [lazy text hPutStr](https://github.com/haskell/text/blob/3f2a71bb1dad5fd8a64f3743b58d765d985723e2/src/Data/Text/Lazy/IO.hs#L132) except that it repeats work for every chunk instead of every char.

**Comment by Bodigrim** [comment]
`NoBuffering` mode is meant to be slow. It does not bear much practical significance, because compiled code uses `LineBuffering` by default.

**Comment by BebeSparkelSparkel** [comment]
I see that now in ghc-internal

```haskell
            hPutChars handle str        -- v. slow, but we don't care
```

https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/ghc-internal/src/GHC/Internal/IO/Handle/Text.hs#L655
