### ISSUE TITLE
Off by one in writeBlocksRaw

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/text#587]
[`writeBlocksRaw`](https://github.com/haskell/text/blob/3f2a71bb1dad5fd8a64f3743b58d765d985723e2/src/Data/Text/IO.hs#L255) uses the same bounds check as [`writeBlocksCRLF`](https://github.com/haskell/text/blob/3f2a71bb1dad5fd8a64f3743b58d765d985723e2/src/Data/Text/IO.hs#L239). `writeBlocksRaw` will always only write one character while `writeBlocksCRLF` can write two.

Seems like it should actually be

```haskell
          | n >= len -> commit n True{-needs flush-} False >>= outer s
```

**Comment by mitchellwrosen** [comment]
Can someone comment on the user-facing impact of this bug?

**Comment by BebeSparkelSparkel** [comment]
Under utilization of the char buffer by one byte.

The only time this would cause a problem is if the char buffer had a size of 1 which is never the case.

**Comment by Bodigrim** [comment]
@mitchellwrosen this is not a vulnerability, just an opportunity to polish.
