### ISSUE TITLE
`streamDecodeUtf8` and `streamDecodeUtf8With` defeat the purpose of the `ByteString` field in `Some Text ByteString (ByteString -> Decoding)`

### ISSUE THREAD

**Issue by michaelt** [haskell/text#60]
This should perhaps be a comment under the heading of https://github.com/bos/text/pull/55 .  The difficulties are outlined a bit laboriously beginning around here https://github.com/michaelt/text-pipes/issues/1#issuecomment-28099431 .  

The difficulty can I think be summed up this way: the user cannot detect from `Some txt bs f` whether `bs` is the beginning of what might end happily as a decent bit of `Text` --  and is thus a fragment already represented in the continuation `f`  -- or whether instead `bs` begins with some genuinely uninterpretable bytes.  For this reason the field is actually useless.  

Because of this we cannot write a (seemingly sensible) function `decodeUtf8 :: Producer ByteString m r -> Producer Text m (Producer ByteString m r)` which would convert a stream of `ByteString` chunks into a stream of `Text` chunks -- but stop when it hits any unsalvageable non-Text and return the remaining `ByteString` producer for further scrutiny.  In the end one is still reduced to a construction like the one in `Conduit.Text` http://hackage.haskell.org/package/conduit-1.0.9.3/docs/src/Data-Conduit-Text.html#byteSplits 

While trying to figure it out I made an uninspired variant of the `Decode` type -- `data Decode = Some Text ByteString (ByteString -> Decode) | Other Text ByteString` and rang corresponding changes in the definition of `streamDecodeWith`.  https://github.com/michaelt/text/commit/942e4c894fbb6cafd8aafdc5c5f148e85ac66dbf#diff-1c42d239accd16adcae29f591c519ac6  I was able to convince myself that all the requisite information could be recovered by a corresponding property in the test suite.  

I hope this is more or less lucid.

**Comment by Bodigrim** [comment]
I believe the original problem is largely fixed in #448 by adding a more powerful streaming interface ([`decodeUtf8Chunk`](https://hackage.haskell.org/package/text-2.1.1/docs/Data-Text-Encoding.html#g:5) and friends) and can be closed. @Lysxia what do you think?
