### ISSUE TITLE
difference between handling precomposed vs decomposed 

### ISSUE THREAD

**Issue by ribosomerocker** [haskell/text#605]
As mentioned in
https://mortoray.com/the-string-type-is-broken/

it seems `TIO.putStrLn (T.reverse (T.pack "noël"))` returns `l̈eon`, which is not what one would expect, and also from the output of the precomposed version, which this snippet uses:
`TIO.putStrLn (T.reverse (T.pack "noël"))`
this outputs: `lëon`, which I think both should output.

**Comment by Lysxia** [comment]
More semantic operations on unicode text can be found in [text-icu](https://hackage.haskell.org/package/text-icu).

Note that the author of that blog post is quite careful about what a correct technical solution would look like:

> I admit the correct answer is not always clear.

also in his previous blog post [We don't need a string type](https://mortoray.com/we-dont-need-a-string-type/):

> I’m now rather convinced there is no need for a special string class. (...) Clearly a rich string library is important, but there is no need for a string class to provide it.

While grapheme clusters make more sense than code points to end users who are looking at the text, the benefits are less clear on the programmatic side. The definition of a grapheme cluster may change with every new version of Unicode, whereas code points have been defined once for all. If you index a text by grapheme clusters and you send that index to another program, you must make sure that they understand the same version of Unicode.

I think of the Haskell text library as a transport solution. Operations on `Text` that fit people's intuitive model of "text" is a UI problem, which can be solved separately in another library such as text-icu.

**Comment by ribosomerocker** [comment]
Thank you!
