### ISSUE TITLE
t_toUpper_char fails on s390x

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#606]
https://github.com/haskell/text/actions/runs/9628836664/job/26557513845 failed with
```
             t_toUpper_char:                            FAIL (0.02s)
              *** Failed! Falsified (after 80 tests):
              '\42954'
              "\42953" /= "\42954"
              Use --quickcheck-replay=567863 to reproduce.
```
I have not looked into it, just filing.

**Comment by Bodigrim** [comment]
Letters in question:
* [Latin Capital Letter S with Short Stroke Overlay](https://www.fileformat.info/info/unicode/char/a7c9/index.htm)
* [Latin Small Letter S with Short Stroke Overlay](https://www.fileformat.info/info/unicode/char/a7ca/index.htm)

**Comment by Lysxia** [comment]
The failing test `t_toUpper_char` is guarded by a [`MIN_VERSION_base(...)` condition](https://github.com/haskell/text/blob/3cd9ed3c1d16ba18986bccbafbb34a4c0b89c564/tests/Tests/Properties/Text.hs#L143) which goes out of date almost every time we upgrade the Unicode version for the case mappings in text.

- GHC 8.8/base 4.13 (what is available in the s390x runner) uses Unicode 12.0
- Those two characters in the failing test case are from Unicode 13.0
- (for the record, text is currently at Unicode 15.0)

**Comment by wismill** [comment]
Related: haskell/core-libraries-committee#278

**Comment by Bodigrim** [comment]
This is now kinda fixed because the `s390x` runner updated from GHC 8.8 to GHC 9.4.
