### ISSUE TITLE
Prepare and release text-2.1.2

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#620]
I think it's time to release a new version of `text`, to be bundled with upcoming GHC 9.12.

@Lysxia any chance you might have spare cycles to update changelog / `@since` pragmas and upload it onto Hackage? I'm unfortunately short on time, at least until next week.

**Comment by Lysxia** [comment]
I'll find some cycles this week.

**Comment by Lysxia** [comment]
Bumping to 2.2 because the new additions feel more substantial than usual.

**Comment by Lysxia** [comment]
[Released on Hackage](https://hackage.haskell.org/package/text-2.1.2)

**Comment by Bodigrim** [comment]
Hooray!
